<?php

namespace ZoweSoft\LaravelCredo\Responses;

use ZoweSoft\LaravelCredo\PaymentBuilder;

/**
 * Typed representation of a successful payment-initialize response from Credo.
 *
 * Returned by {@see PaymentBuilder::send()}.
 * Redirect the customer to {@see self::$authorizationUrl} to display the
 * Credo hosted checkout.
 *
 * @see https://docs.credocentral.com/docs/developers/initialize-transaction
 */
class InitializeResponse
{
    /**
     * @param  string  $authorizationUrl  The Credo-hosted checkout URL to redirect the customer to.
     * @param  string  $reference  Your business reference (echoed from the request, or
     *                             auto-generated by Credo if none was provided).
     * @param  string  $credoReference  Credo's own reference for this transaction.
     * @param  string|null  $crn  Credo Reference Number — an alternative short reference
     *                            used in some Credo interfaces; may be null.
     * @param  array<string, mixed>  $raw  Full API response object for forward-compatibility.
     */
    public function __construct(
        public readonly string $authorizationUrl,
        public readonly string $reference,
        public readonly string $credoReference,
        public readonly ?string $crn,
        public readonly array $raw = [],
    ) {}

    /**
     * @param  array<string, mixed>  $data
     * @param  array<string, mixed>  $requestPayload
     */
    public static function fromArray(array $data, array $requestPayload = []): self
    {
        return new self(
            authorizationUrl: (string) ($data['authorizationUrl'] ?? ''),
            reference: (string) ($data['reference'] ?? ($requestPayload['reference'] ?? '')),
            credoReference: (string) ($data['credoReference'] ?? ''),
            crn: $data['crn'] ?? null,
            raw: $data,
        );
    }
}
